services:
  - type: web
    name: ai-maintenance-reporter
    runtime: python
    buildCommand: pip install -r requirements.txt && cd frontend && npm install && npm run build && cd ..
    startCommand: uvicorn backend.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.4
      - key: DATABASE_URL
        fromDatabase:
          name: ai-maintenance-db
          property: connectionString
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: GEMINI_API_KEY
        sync: false
